/* vim: ft=maxima
*/

/* generic unit tests */

/* apply function to each element of inputs in turn. If the output isn't
 * equal to the corresponding element of outputs, display the input,
 * expected output, actual output
 */
unittests(function, inputs, outputs) := block([i, actualOutput, expectedOutput, flag],
    flag : true,
    for i : 1 thru length(inputs) do (
        actualOutput : function(inputs[i]),
        expectedOutput : outputs[i],
        if actualOutput # expectedOutput then (
            flag : false,
            print("test failed. input:", inputs[i], "expected output:", expectedOutput, "actual output:", actualOutput)
        )
    ),
    if flag then "all tests passed"
);

/* example:
 * f(x) := x ** 2 ;
 * ip : [-1, 1, 2, 3];
 * op : [1, 1, 4, 8];
 * unittests(f, ip, op);
 * will print an error message because f(ip[3]) # op[3]
 */

